# -*- coding: utf-8 -*-
"""
Strategy Report HTML Renderer.

Renders the Jinja2 template with section content and cover metadata.
Shared between routes/strategy.py (HTML/PDF endpoints) and
services/strategy_pipeline.py (post-generation PDF).
"""
from __future__ import annotations

import logging
import os
from datetime import datetime
from typing import Any

from jinja2 import Environment, FileSystemLoader

logger = logging.getLogger(__name__)


def render_strategy_html(sr: Any, db_session: Any) -> str:
    """
    Render strategy report HTML from Jinja2 template.

    Args:
        sr: StrategyReport ORM object (must have .sections, .briefing_id, .updated_at)
        db_session: SQLAlchemy session for loading Briefing + Analysis
    """
    from models import Briefing, Analysis

    template_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "templates")
    env = Environment(loader=FileSystemLoader(template_dir), autoescape=False)
    template = env.get_template("strategy_report.html")

    briefing = db_session.query(Briefing).filter(Briefing.id == sr.briefing_id).first()
    briefing_data = (briefing.answers if briefing else {}) or {}

    # Load Report 1 data for scores and metadata
    analysis = db_session.query(Analysis).filter(
        Analysis.briefing_id == sr.briefing_id
    ).first()
    report1_meta = (analysis.meta if analysis else {}) or {}
    report1_sections = report1_meta.get("sections", {})

    # Extract score + reifegrad from Report 1
    readiness_score = report1_sections.get("score_gesamt", "")
    if not readiness_score:
        readiness_score = report1_meta.get("scores", {}).get("overall", "")
    reifegrad_label = report1_sections.get("score_rating", "")

    # Branche: capitalize for display
    branche_raw = briefing_data.get("branche", "")
    branche_label = branche_raw.title() if branche_raw else ""

    # Research date from report1 or generation date
    research_date = report1_meta.get("research_last_updated", "")
    if not research_date:
        research_date = (sr.updated_at or datetime.now()).strftime("%d.%m.%Y")

    # Segment label
    segment_map = {
        "solo": "Einzelunternehmer",
        "team": "Kleinunternehmen (2-10 MA)",
        "kmu": "KMU (11-250 MA)",
    }
    segment_raw = briefing_data.get("unternehmensgroesse", "")
    segment_label = segment_map.get(segment_raw.lower(), segment_raw) if segment_raw else ""

    # Mitarbeiter
    mitarbeiter = briefing_data.get("mitarbeiter", "")

    # Nächste Schritte: use static template if not generated by LLM
    sections = sr.sections or {}
    naechste_schritte = sections.get("naechste_schritte", "")
    if not naechste_schritte:
        from prompts.strategy_prompts import SECTION_TEMPLATE_NAECHSTE_SCHRITTE
        naechste_schritte = SECTION_TEMPLATE_NAECHSTE_SCHRITTE

    context = {
        # Cover metadata
        "firmenname": briefing_data.get("unternehmen_name", "Ihr Unternehmen"),
        "branche": branche_label,
        "datum": datetime.now().strftime("%d.%m.%Y"),
        "segment": segment_label,
        "mitarbeiter": mitarbeiter,
        "readiness_score": readiness_score,
        "reifegrad_label": reifegrad_label,
        "research_date": research_date,
        "report_id": f"STR-{sr.briefing_id}",
        "build_id": os.getenv("BUILD_ID", ""),
        # Sections
        "exec_summary": sections.get("exec_summary", ""),
        "section_s1": sections.get("S1", ""),
        "section_s2": sections.get("S2", ""),
        "section_s3": sections.get("S3", ""),
        "section_s4": sections.get("S4", ""),
        "section_s5": sections.get("S5", ""),
        "section_s6": sections.get("S6", ""),
        "section_s7": sections.get("S7", ""),
        "section_s8": sections.get("S8", ""),
        "naechste_schritte": naechste_schritte,
    }

    return str(template.render(**context))
